import { Ionicons } from '@expo/vector-icons';
import { Pressable, StyleSheet, View } from 'react-native';

import { FormField } from '@/components/auth/auth-form';
import { TimeRangeField } from '@/components/class-schedules/time-range-field';
import { WeekdayPicker } from '@/components/class-schedules/weekday-picker';
import { ThemedText } from '@/components/themed-text';
import { DesignTokens } from '@/constants/theme';
import { useAppearance } from '@/contexts/appearance-context';
import type { ClassScheduleFormErrors, ClassScheduleFormField, ClassScheduleFormValues } from '@/lib/class-schedules/class-schedule-form';

export function CourseScheduleEditor({ errors, onAdd, onChange, onRemove, schedules }: { errors: ClassScheduleFormErrors[]; onAdd: () => void; onChange: (index: number, values: ClassScheduleFormValues) => void; onRemove: (index: number) => void; schedules: ClassScheduleFormValues[] }) {
  const { colors } = useAppearance();
  function update<Field extends ClassScheduleFormField>(index: number, field: Field, value: ClassScheduleFormValues[Field]) { onChange(index, { ...schedules[index], [field]: value }); }
  return <View style={styles.section}><View style={styles.heading}><View style={styles.headingText}><ThemedText type="defaultSemiBold">Schedule</ThemedText><ThemedText style={[styles.hint, { color: colors.textSecondary }]}>Optional · add one record per weekly meeting</ThemedText></View><Pressable accessibilityRole="button" onPress={onAdd} style={({ pressed }) => [styles.add, { borderColor: colors.border }, pressed ? styles.pressed : undefined]}><Ionicons color={colors.primary} name="add" size={16} /><ThemedText style={[styles.addLabel, { color: colors.primary }]}>Add</ThemedText></Pressable></View>
    {schedules.map((schedule, index) => <View key={index} style={[styles.card, { backgroundColor: colors.surfaceSubtle, borderColor: colors.border }]}><View style={styles.cardHeading}><ThemedText style={styles.cardTitle}>Meeting {index + 1}</ThemedText><Pressable accessibilityLabel={`Remove meeting ${index + 1}`} accessibilityRole="button" onPress={() => onRemove(index)} style={styles.remove}><Ionicons color={colors.danger} name="trash-outline" size={17} /></Pressable></View><WeekdayPicker onChange={(value) => update(index, 'weekday', value)} value={schedule.weekday} /><TimeRangeField endError={errors[index]?.endTime} endTime={schedule.endTime} onEndChange={(value) => update(index, 'endTime', value)} onStartChange={(value) => update(index, 'startTime', value)} startError={errors[index]?.startTime} startTime={schedule.startTime} /><FormField error={errors[index]?.room} label="Room (optional)" onChangeText={(value) => update(index, 'room', value)} placeholder="Room 204" value={schedule.room} /><View style={styles.row}><View style={styles.flex}><FormField error={errors[index]?.startDate} keyboardType="numbers-and-punctuation" label="Starts" onChangeText={(value) => update(index, 'startDate', value)} placeholder="YYYY-MM-DD" value={schedule.startDate} /></View><View style={styles.flex}><FormField error={errors[index]?.endDate} keyboardType="numbers-and-punctuation" label="Ends" onChangeText={(value) => update(index, 'endDate', value)} placeholder="YYYY-MM-DD" value={schedule.endDate} /></View></View></View>)}
    {!schedules.length ? <Pressable accessibilityRole="button" onPress={onAdd} style={({ pressed }) => [styles.empty, { borderColor: colors.border }, pressed ? styles.pressed : undefined]}><ThemedText style={[styles.hint, { color: colors.textSecondary }]}>+ Add a weekly class meeting</ThemedText></Pressable> : null}
  </View>;
}
const styles = StyleSheet.create({ section: { gap: DesignTokens.spacing.sm }, heading: { alignItems: 'center', flexDirection: 'row', gap: DesignTokens.spacing.sm }, headingText: { flex: 1 }, hint: { fontSize: 11, lineHeight: 16 }, add: { alignItems: 'center', borderRadius: DesignTokens.radius.md, borderWidth: 1, flexDirection: 'row', gap: 3, minHeight: 38, paddingHorizontal: DesignTokens.spacing.sm }, addLabel: { fontSize: 12, fontWeight: '700' }, card: { borderRadius: DesignTokens.radius.lg, borderWidth: StyleSheet.hairlineWidth, gap: DesignTokens.spacing.md, padding: DesignTokens.spacing.md }, cardHeading: { alignItems: 'center', flexDirection: 'row' }, cardTitle: { flex: 1, fontSize: 13, fontWeight: '700' }, remove: { alignItems: 'center', height: 36, justifyContent: 'center', width: 36 }, row: { flexDirection: 'row', gap: DesignTokens.spacing.sm }, flex: { flex: 1 }, empty: { alignItems: 'center', borderRadius: DesignTokens.radius.md, borderStyle: 'dashed', borderWidth: 1, minHeight: 44, justifyContent: 'center' }, pressed: { opacity: 0.62 } });
