import { Ionicons } from '@expo/vector-icons';
import { Modal, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { ThemedText } from '@/components/themed-text';
import { DesignTokens, Shadows } from '@/constants/theme';
import { useAppearance } from '@/contexts/appearance-context';

export type SheetAction = { icon: keyof typeof Ionicons.glyphMap; label: string; description?: string; closeOnPress?: boolean; onPress: () => void };

export function BottomActionSheet({ actions, compact = false, onClose, title, visible }: { actions: SheetAction[]; compact?: boolean; onClose: () => void; title: string; visible: boolean }) {
  const { colors } = useAppearance();
  return <Modal animationType="slide" onRequestClose={onClose} transparent visible={visible}><View style={styles.overlay}><Pressable accessibilityLabel="Close actions" accessibilityRole="button" onPress={onClose} style={StyleSheet.absoluteFill} /><SafeAreaView edges={['bottom']} style={[styles.sheet, { backgroundColor: colors.surface, borderColor: colors.outline }]}><View style={[styles.handle, { backgroundColor: colors.outline }]} /><View style={styles.header}><ThemedText type="subtitle">{title}</ThemedText><Pressable accessibilityLabel="Close" accessibilityRole="button" onPress={onClose} style={styles.close}><Ionicons color={colors.textSecondary} name="close" size={DesignTokens.icon.lg} /></Pressable></View><ScrollView contentContainerStyle={[styles.actions, compact ? styles.compactActions : undefined]}>{actions.map((action) => <Pressable accessibilityRole="button" key={action.label} onPress={() => { if (action.closeOnPress !== false) onClose(); action.onPress(); }} style={({ pressed }) => [styles.action, compact ? styles.compactAction : undefined, { backgroundColor: colors.surfaceVariant }, pressed ? styles.pressed : undefined]}><View style={[styles.actionIcon, compact ? styles.compactActionIcon : undefined, { backgroundColor: colors.primaryContainer }]}><Ionicons color={colors.primary} name={action.icon} size={compact ? DesignTokens.icon.md : DesignTokens.icon.lg} /></View><View style={styles.actionText}><ThemedText type="defaultSemiBold">{action.label}</ThemedText>{action.description ? <ThemedText style={{ color: colors.textSecondary }}>{action.description}</ThemedText> : null}</View>{compact ? null : <Ionicons color={colors.textSecondary} name="chevron-forward" size={DesignTokens.icon.md} />}</Pressable>)}</ScrollView></SafeAreaView></View></Modal>;
}

const styles = StyleSheet.create({ overlay: { backgroundColor: 'rgba(0,0,0,0.38)', flex: 1, justifyContent: 'flex-end' }, sheet: { borderTopLeftRadius: DesignTokens.radius.xxl, borderTopRightRadius: DesignTokens.radius.xxl, borderWidth: StyleSheet.hairlineWidth, maxHeight: '78%', paddingTop: DesignTokens.spacing.sm, ...Shadows }, handle: { alignSelf: 'center', borderRadius: DesignTokens.radius.pill, height: 4, opacity: 0.45, width: 42 }, header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: DesignTokens.layout.screenPadding, paddingVertical: DesignTokens.spacing.md }, close: { alignItems: 'center', height: DesignTokens.size.touchTarget, justifyContent: 'center', width: DesignTokens.size.touchTarget }, actions: { gap: DesignTokens.spacing.sm, paddingHorizontal: DesignTokens.layout.screenPadding, paddingBottom: DesignTokens.spacing.xl }, compactActions: { gap: DesignTokens.spacing.xs }, action: { alignItems: 'center', borderRadius: DesignTokens.radius.lg, flexDirection: 'row', gap: DesignTokens.spacing.md, minHeight: 72, padding: DesignTokens.spacing.md }, compactAction: { minHeight: 52, paddingHorizontal: DesignTokens.spacing.md, paddingVertical: DesignTokens.spacing.sm }, actionIcon: { alignItems: 'center', borderRadius: DesignTokens.radius.md, height: 44, justifyContent: 'center', width: 44 }, compactActionIcon: { height: 32, width: 32 }, actionText: { flex: 1, gap: 2 }, pressed: { opacity: 0.72 } });
