import { Ionicons } from '@expo/vector-icons';
import { Pressable, ScrollView, StyleSheet, View } from 'react-native';

import { ThemedText } from '@/components/themed-text';
import { AppBottomSheet } from '@/components/ui/app-bottom-sheet';
import { DesignTokens } from '@/constants/theme';
import { useAppearance } from '@/contexts/appearance-context';

export type SheetAction = { icon: keyof typeof Ionicons.glyphMap; label: string; description?: string; closeOnPress?: boolean; onPress: () => void };
export function BottomActionSheet({ actions, compact = false, onClose, title, visible }: { actions: SheetAction[]; compact?: boolean; onClose: () => void; title: string; visible: boolean }) { const { colors } = useAppearance(); return <AppBottomSheet expandable initialSnap={compact ? 0.52 : 0.68} onClose={onClose} title={title} visible={visible}><ScrollView contentContainerStyle={[styles.actions, compact ? styles.compactActions : undefined]}>{actions.map((action) => <Pressable accessibilityRole="button" key={action.label} onPress={() => { if (action.closeOnPress !== false) onClose(); action.onPress(); }} style={({ pressed }) => [styles.action, compact ? styles.compactAction : undefined, { backgroundColor: colors.surfaceVariant, borderColor: colors.border }, pressed ? styles.pressed : undefined]}><View style={[styles.actionIcon, compact ? styles.compactActionIcon : undefined, { backgroundColor: colors.primaryContainer }]}><Ionicons color={colors.primary} name={action.icon} size={compact ? DesignTokens.icon.md : DesignTokens.icon.lg} /></View><View style={styles.actionText}><ThemedText style={styles.label}>{action.label}</ThemedText>{action.description ? <ThemedText style={[styles.description, { color: colors.textSecondary }]}>{action.description}</ThemedText> : null}</View>{compact ? null : <Ionicons color={colors.textSecondary} name="chevron-forward" size={DesignTokens.icon.md} />}</Pressable>)}</ScrollView></AppBottomSheet>; }
const styles = StyleSheet.create({ actions: { gap: DesignTokens.spacing.sm, paddingBottom: DesignTokens.spacing.xl, paddingHorizontal: DesignTokens.layout.screenPadding }, compactActions: { gap: DesignTokens.spacing.xs }, action: { alignItems: 'center', borderRadius: DesignTokens.radius.lg, borderWidth: StyleSheet.hairlineWidth, flexDirection: 'row', gap: DesignTokens.spacing.md, minHeight: 66, padding: DesignTokens.spacing.md }, compactAction: { minHeight: 50, paddingHorizontal: DesignTokens.spacing.md, paddingVertical: DesignTokens.spacing.sm }, actionIcon: { alignItems: 'center', borderRadius: DesignTokens.radius.md, height: 40, justifyContent: 'center', width: 40 }, compactActionIcon: { height: 30, width: 30 }, actionText: { flex: 1, gap: 2 }, label: { fontSize: 12, fontWeight: '700', lineHeight: 16 }, description: { fontSize: 10, lineHeight: 14 }, pressed: { opacity: 0.72 } });
