import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { ThemedText } from '@/components/themed-text';
import { DesignTokens, Shadows } from '@/constants/theme';
import { useAppearance } from '@/contexts/appearance-context';
import type { Course } from '@/lib/api/course.types';

export function CourseSelectField({ courses, label = 'Course', onChange, value }: { courses: Course[]; label?: string; onChange: (courseId: string | null) => void; value: string | null }) {
  const { colors } = useAppearance();
  const [visible, setVisible] = useState(false);
  const selected = courses.find((course) => course.id === value);
  return <View style={styles.field}><ThemedText style={styles.label}>{label}</ThemedText><Pressable accessibilityLabel={`${label}, ${selected?.code ?? selected?.name ?? 'Personal'}`} accessibilityRole="button" onPress={() => setVisible(true)} style={({ pressed }) => [styles.trigger, { backgroundColor: colors.surface, borderColor: colors.border }, pressed ? styles.pressed : undefined]}><View style={styles.selectedText}><ThemedText numberOfLines={1} style={styles.selectedTitle}>{selected?.code ?? selected?.name ?? 'Personal'}</ThemedText>{selected?.code ? <ThemedText numberOfLines={1} style={[styles.selectedSubtitle, { color: colors.textSecondary }]}>{selected.name}</ThemedText> : null}</View><Ionicons color={colors.textSecondary} name="chevron-down" size={17} /></Pressable>
    <Modal animationType="slide" onRequestClose={() => setVisible(false)} transparent visible={visible}><View style={styles.overlay}><Pressable accessibilityLabel="Close course selector" onPress={() => setVisible(false)} style={StyleSheet.absoluteFill} /><SafeAreaView edges={['bottom']} style={[styles.sheet, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.handle, { backgroundColor: colors.border }]} /><View style={styles.header}><ThemedText style={styles.title}>Select course</ThemedText><Pressable accessibilityLabel="Close" onPress={() => setVisible(false)} style={styles.close}><Ionicons color={colors.textSecondary} name="close" size={20} /></Pressable></View><ScrollView contentContainerStyle={styles.options}><CourseOption onPress={() => { onChange(null); setVisible(false); }} selected={value === null} subtitle="Not linked to a course" title="Personal" />{courses.map((course) => <CourseOption key={course.id} onPress={() => { onChange(course.id); setVisible(false); }} selected={course.id === value} subtitle={course.code ? course.name : undefined} title={course.code ?? course.name} />)}</ScrollView></SafeAreaView></View></Modal>
  </View>;
}

function CourseOption({ onPress, selected, subtitle, title }: { onPress: () => void; selected: boolean; subtitle?: string; title: string }) { const { colors } = useAppearance(); return <Pressable accessibilityRole="button" accessibilityState={{ selected }} onPress={onPress} style={({ pressed }) => [styles.option, { backgroundColor: selected ? colors.primaryContainer : colors.surfaceSubtle, borderColor: selected ? colors.primary : colors.border }, pressed ? styles.pressed : undefined]}><View style={styles.optionText}><ThemedText numberOfLines={1} style={styles.optionTitle}>{title}</ThemedText>{subtitle ? <ThemedText numberOfLines={1} style={[styles.optionSubtitle, { color: colors.textSecondary }]}>{subtitle}</ThemedText> : null}</View>{selected ? <Ionicons color={colors.primary} name="checkmark-circle" size={20} /> : null}</Pressable>; }
const styles = StyleSheet.create({ field: { gap: 7 }, label: { fontSize: 12, fontWeight: '700', lineHeight: 16 }, trigger: { alignItems: 'center', borderRadius: DesignTokens.radius.md, borderWidth: 1, flexDirection: 'row', minHeight: 48, paddingHorizontal: DesignTokens.spacing.md }, selectedText: { flex: 1, minWidth: 0 }, selectedTitle: { fontSize: 13, fontWeight: '700', lineHeight: 17 }, selectedSubtitle: { fontSize: 10, lineHeight: 13 }, pressed: { opacity: 0.67 }, overlay: { backgroundColor: 'rgba(12, 15, 18, 0.42)', flex: 1, justifyContent: 'flex-end' }, sheet: { borderTopLeftRadius: DesignTokens.radius.xxl, borderTopRightRadius: DesignTokens.radius.xxl, borderWidth: StyleSheet.hairlineWidth, maxHeight: '68%', paddingTop: DesignTokens.spacing.sm, ...Shadows }, handle: { alignSelf: 'center', borderRadius: 999, height: 4, opacity: 0.5, width: 42 }, header: { alignItems: 'center', flexDirection: 'row', paddingHorizontal: DesignTokens.layout.screenPadding, paddingVertical: DesignTokens.spacing.sm }, title: { flex: 1, fontSize: 17, fontWeight: '800' }, close: { alignItems: 'center', height: 44, justifyContent: 'center', width: 44 }, options: { gap: DesignTokens.spacing.xs, paddingHorizontal: DesignTokens.layout.screenPadding, paddingBottom: DesignTokens.spacing.xl }, option: { alignItems: 'center', borderRadius: DesignTokens.radius.md, borderWidth: StyleSheet.hairlineWidth, flexDirection: 'row', minHeight: 54, paddingHorizontal: DesignTokens.spacing.md, paddingVertical: DesignTokens.spacing.sm }, optionText: { flex: 1, minWidth: 0 }, optionTitle: { fontSize: 13, fontWeight: '700', lineHeight: 17 }, optionSubtitle: { fontSize: 10.5, lineHeight: 14 } });
