import { Ionicons } from '@expo/vector-icons';
import { useEffect, useState } from 'react';
import { Modal, Pressable, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { ThemedText } from '@/components/themed-text';
import { DesignTokens, Shadows } from '@/constants/theme';
import { useAppearance } from '@/contexts/appearance-context';
import { getMonthDays, monthTitle, parseLocalDate, toLocalDateKey } from '@/lib/calendar/calendar-date';

const WEEKDAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

export function DatePickerField({ allowClear = false, displayFormat = 'medium', error, hideLabel = false, label, onChange, pickerTitle, placeholder = 'Set date', value }: { allowClear?: boolean; displayFormat?: 'compact' | 'medium'; error?: string; hideLabel?: boolean; label: string; onChange: (value: string) => void; pickerTitle?: string; placeholder?: string; value: string }) {
  const { colors } = useAppearance();
  const [visible, setVisible] = useState(false);
  const [draft, setDraft] = useState(value);
  const [month, setMonth] = useState(() => monthFor(value));
  useEffect(() => { if (visible) { setDraft(value || toLocalDateKey(new Date())); setMonth(monthFor(value)); } }, [value, visible]);
  const parsed = parseLocalDate(value);
  const labelValue = parsed?.toLocaleDateString(undefined, displayFormat === 'compact' ? { month: 'short', day: 'numeric' } : { month: 'short', day: 'numeric', year: 'numeric' }) ?? placeholder;
  const chooseQuickDate = (offset: number) => { const now = new Date(); const next = new Date(now.getFullYear(), now.getMonth(), now.getDate() + offset); const nextValue = toLocalDateKey(next); setDraft(nextValue); setMonth(new Date(next.getFullYear(), next.getMonth(), 1)); };

  return <View style={styles.field}>
    {!hideLabel ? <ThemedText style={styles.label}>{label}</ThemedText> : null}
    <Pressable accessibilityLabel={`${label}, ${labelValue}`} accessibilityRole="button" onPress={() => setVisible(true)} style={({ pressed }) => [styles.trigger, { backgroundColor: colors.surface, borderColor: error ? colors.danger : colors.border }, pressed ? styles.pressed : undefined]}><ThemedText numberOfLines={1} style={[styles.value, !parsed ? { color: colors.textMuted } : undefined]}>{labelValue}</ThemedText><Ionicons color={colors.primary} name="calendar-outline" size={17} /></Pressable>
    {error ? <ThemedText style={[styles.error, { color: colors.dangerText }]}>{error}</ThemedText> : null}
    <Modal animationType="slide" onRequestClose={() => setVisible(false)} transparent visible={visible}><View style={styles.overlay}><Pressable accessibilityLabel="Close date picker" onPress={() => setVisible(false)} style={StyleSheet.absoluteFill} /><SafeAreaView edges={['bottom']} style={[styles.sheet, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.handle, { backgroundColor: colors.border }]} /><View style={styles.titleRow}><ThemedText style={styles.title}>{pickerTitle ?? `Select ${label.toLowerCase()}`}</ThemedText></View>
      <View style={styles.monthHeader}><Pressable accessibilityLabel="Previous month" onPress={() => setMonth((current) => new Date(current.getFullYear(), current.getMonth() - 1, 1))} style={styles.iconButton}><Ionicons color={colors.primary} name="chevron-back" size={20} /></Pressable><ThemedText style={styles.month}>{monthTitle(month)}</ThemedText><Pressable accessibilityLabel="Next month" onPress={() => setMonth((current) => new Date(current.getFullYear(), current.getMonth() + 1, 1))} style={styles.iconButton}><Ionicons color={colors.primary} name="chevron-forward" size={20} /></Pressable></View>
      <View style={styles.weekRow}>{WEEKDAYS.map((day) => <ThemedText key={day} style={[styles.weekday, { color: colors.textMuted }]}>{day}</ThemedText>)}</View>
      <View style={styles.grid}>{getMonthDays(month).map((day) => { const isSelected = day.date === draft; return <Pressable accessibilityLabel={day.date} accessibilityRole="button" accessibilityState={{ selected: isSelected }} key={day.date} onPress={() => setDraft(day.date)} style={({ pressed }) => [styles.day, isSelected ? { backgroundColor: colors.primary } : undefined, day.date === toLocalDateKey(new Date()) && !isSelected ? { borderColor: colors.primary, borderWidth: 1 } : undefined, pressed ? styles.pressed : undefined]}><ThemedText style={[styles.dayText, { color: isSelected ? colors.primaryText : day.isCurrentMonth ? colors.text : colors.textMuted }]}>{day.dayNumber}</ThemedText></Pressable>; })}</View>
      <View style={styles.quickRow}><QuickAction label="Today" onPress={() => chooseQuickDate(0)} /><QuickAction label="Tomorrow" onPress={() => chooseQuickDate(1)} />{allowClear ? <QuickAction label="Clear" onPress={() => setDraft('')} /> : null}</View>
      <View style={[styles.footer, { borderTopColor: colors.border }]}><Pressable onPress={() => setVisible(false)} style={styles.footerAction}><ThemedText style={{ color: colors.textSecondary, fontWeight: '700' }}>Cancel</ThemedText></Pressable><Pressable onPress={() => { onChange(draft); setVisible(false); }} style={[styles.done, { backgroundColor: colors.primary }]}><ThemedText style={{ color: colors.primaryText, fontWeight: '700' }}>Done</ThemedText></Pressable></View>
    </SafeAreaView></View></Modal>
  </View>;
}

function QuickAction({ label, onPress }: { label: string; onPress: () => void }) { const { colors } = useAppearance(); return <Pressable onPress={onPress} style={({ pressed }) => [styles.quick, { backgroundColor: colors.surfaceSubtle, borderColor: colors.border }, pressed ? styles.pressed : undefined]}><ThemedText style={[styles.quickLabel, { color: colors.primary }]}>{label}</ThemedText></Pressable>; }
function monthFor(value: string): Date { const selected = parseLocalDate(value) ?? new Date(); return new Date(selected.getFullYear(), selected.getMonth(), 1); }
const styles = StyleSheet.create({ field: { flex: 1, gap: 7, minWidth: 0 }, label: { fontSize: 13, fontWeight: '600', lineHeight: 18 }, trigger: { alignItems: 'center', borderRadius: DesignTokens.radius.md, borderWidth: 1, flexDirection: 'row', gap: 6, minHeight: 44, paddingHorizontal: 10 }, value: { flex: 1, fontSize: 12, fontWeight: '600' }, error: { fontSize: 11, lineHeight: 15 }, pressed: { opacity: 0.68 }, overlay: { backgroundColor: 'rgba(12, 15, 18, 0.42)', flex: 1, justifyContent: 'flex-end' }, sheet: { borderTopLeftRadius: DesignTokens.radius.xxl, borderTopRightRadius: DesignTokens.radius.xxl, borderWidth: StyleSheet.hairlineWidth, paddingTop: DesignTokens.spacing.sm, ...Shadows }, handle: { alignSelf: 'center', borderRadius: 999, height: 4, opacity: 0.5, width: 42 }, titleRow: { paddingHorizontal: DesignTokens.layout.screenPadding, paddingTop: DesignTokens.spacing.sm }, title: { fontSize: 17, fontWeight: '800', lineHeight: 22 }, monthHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: DesignTokens.spacing.md }, iconButton: { alignItems: 'center', height: 42, justifyContent: 'center', width: 42 }, month: { fontSize: 15, fontWeight: '700' }, weekRow: { flexDirection: 'row', paddingHorizontal: DesignTokens.spacing.md }, weekday: { flex: 1, fontSize: 10, fontWeight: '700', textAlign: 'center' }, grid: { flexDirection: 'row', flexWrap: 'wrap', paddingHorizontal: DesignTokens.spacing.md }, day: { alignItems: 'center', borderRadius: 10, height: 38, justifyContent: 'center', width: '14.2857%' }, dayText: { fontSize: 12, fontWeight: '600' }, quickRow: { flexDirection: 'row', gap: DesignTokens.spacing.sm, padding: DesignTokens.spacing.md }, quick: { alignItems: 'center', borderRadius: DesignTokens.radius.pill, borderWidth: StyleSheet.hairlineWidth, justifyContent: 'center', minHeight: 36, paddingHorizontal: DesignTokens.spacing.md }, quickLabel: { fontSize: 11, fontWeight: '700' }, footer: { borderTopWidth: StyleSheet.hairlineWidth, flexDirection: 'row', gap: DesignTokens.spacing.sm, paddingHorizontal: DesignTokens.layout.screenPadding, paddingTop: DesignTokens.spacing.md }, footerAction: { alignItems: 'center', flex: 1, justifyContent: 'center', minHeight: 44 }, done: { alignItems: 'center', borderRadius: DesignTokens.radius.md, flex: 1, justifyContent: 'center', minHeight: 44 } });
