import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { generateClassScheduleOccurrences } from './occurrences.ts';
import { zonedWallClockToIso } from './zoned-date-time.ts';

const course = { id: 'course-1', name: 'Programming', code: 'CS 101', color: '#3366FF' };
function schedule(overrides = {}) { return { id: 'schedule-1', userId: 'user-1', courseId: course.id, weekday: 'MONDAY', startTime: '08:00', endTime: '09:30', room: 'Lab 2', startDate: '2024-01-01', endDate: '2027-01-01', createdAt: '', updatedAt: '', scheduleGroupId: 'group-1', timezone: 'Asia/Manila', courseArchived: false, holidayDates: [], exceptions: [], ...overrides }; }
function range(firstDate, lastDate) { return { from: '', to: '', firstDate, lastDate }; }

test('includes exact semester boundaries and leap day', () => { const items = generateClassScheduleOccurrences([schedule({ weekday: 'THURSDAY', startDate: '2024-02-29', endDate: '2024-02-29' })], [course], range('2024-02-29', '2024-02-29')); assert.equal(items.length, 1); assert.equal(items[0].date, '2024-02-29'); });
test('handles month and year boundaries', () => { const items = generateClassScheduleOccurrences([schedule()], [course], range('2024-12-29', '2025-01-07')); assert.deepEqual(items.map((item) => item.date), ['2024-12-30', '2025-01-06']); });
test('holiday and cancellation suppress only their occurrences', () => { const value = schedule({ holidayDates: ['2026-08-24'], exceptions: [{ id: 'ex', date: '2026-08-31', cancelled: true, startTimeOverride: null, endTimeOverride: null, roomOverride: null }] }); assert.deepEqual(generateClassScheduleOccurrences([value], [course], range('2026-08-17', '2026-09-07')).map((item) => item.date), ['2026-08-17', '2026-09-07']); });
test('one-time time and room overrides affect only one occurrence', () => { const value = schedule({ exceptions: [{ id: 'ex', date: '2026-09-07', cancelled: false, startTimeOverride: '10:00', endTimeOverride: '11:30', roomOverride: 'Lab 3' }] }); const items = generateClassScheduleOccurrences([value], [course], range('2026-08-31', '2026-09-14')); assert.deepEqual(items.map((item) => [item.date, new Date(item.startAt).toLocaleTimeString('en-US', { timeZone: 'Asia/Manila', hour: '2-digit', minute: '2-digit', hour12: false }), item.location]), [['2026-08-31', '08:00', 'Lab 2'], ['2026-09-07', '10:00', 'Lab 3'], ['2026-09-14', '08:00', 'Lab 2']]); });
test('archived courses do not generate current occurrences', () => { assert.equal(generateClassScheduleOccurrences([schedule({ courseArchived: true })], [course], range('2026-08-17', '2026-08-17')).length, 0); });
test('Asia/Manila converts local wall time to the expected instant', () => { assert.equal(zonedWallClockToIso('2026-08-17', '08:00', 'Asia/Manila'), '2026-08-17T00:00:00.000Z'); });
test('DST offset changes while local wall clock remains 08:00', () => { const winter = zonedWallClockToIso('2026-03-02', '08:00', 'America/New_York'); const summer = zonedWallClockToIso('2026-03-16', '08:00', 'America/New_York'); assert.equal(winter, '2026-03-02T13:00:00.000Z'); assert.equal(summer, '2026-03-16T12:00:00.000Z'); for (const instant of [winter, summer]) assert.equal(new Date(instant).toLocaleTimeString('en-US', { timeZone: 'America/New_York', hour: '2-digit', minute: '2-digit', hour12: false }), '08:00'); });
test('spring-forward and fall-back dates convert to valid instants', () => { assert.ok(zonedWallClockToIso('2026-03-08', '03:30', 'America/New_York')); assert.ok(zonedWallClockToIso('2026-11-01', '01:30', 'America/New_York')); });
test('time range owns one picker instance and one activePicker state', async () => { const source = await readFile(new URL('../../components/class-schedules/time-range-field.tsx', import.meta.url), 'utf8'); assert.equal((source.match(/<DateTimePicker\b/g) ?? []).length, 1); assert.equal((source.match(/useState<ActivePicker>/g) ?? []).length, 1); assert.doesNotMatch(source, /showStartPicker|showEndPicker/); });
